services:
  dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.dev

  prod-dist:
    build:
      context: .
      dockerfile: docker/prod-dist.Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  prod-binary:
    build:
      context: .
      dockerfile: docker/prod-binary.Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env.bin.prod
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
